#!/usr/bin/env python3
import sys, tty, termios
from ev3dev2.motor import LargeMotor, OUTPUT_C

motor = LargeMotor(OUTPUT_C)
SPEED = 50

def get_key():
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        return sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)

print("Tryk F (frem) eller B (baglæns), S for stop, X for exit.")

while True:
    key = get_key().lower()

    if key == 'f':
        motor.on(SPEED)
        print("Frem")
    elif key == 'b':
        motor.on(-SPEED)
        print("Baglæns")
    elif key == 's':
        motor.off()
        print("Stop")
    elif key == 'x':
        motor.off()
        print("Afslutter...")
        break

